import { ThemeDefinition, ThemeId } from "@/lib/types";

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  anger: {
    id: "anger",
    label: "Anger",
    tagline: "Pause before your reaction becomes your regret.",
    accentClass: "from-orange-500 to-rose-500",
    surfaceClass: "bg-orange-50",
    borderClass: "border-orange-200",
    icon: "Flame",
    keywords: ["angry", "anger", "mad", "furious", "rage", "shout", "yell", "fight", "argue", "annoyed"],
    ayah: {
      reference: "3:134",
      source: "Al Quran Cloud fallback cache",
      arabic: "وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ ۗ وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ",
      english: "Those who restrain anger and pardon people. Allah loves those who do good.",
      urdu: "اور جو غصہ پی جاتے ہیں اور لوگوں کو معاف کر دیتے ہیں، اور اللہ احسان کرنے والوں سے محبت کرتا ہے۔",
    },
    explanation:
      "Islam does not reward a loud reaction. It praises control, mercy, and the ability to step back before harm spreads.",
    actionSteps: [
      "Leave the argument for two minutes before replying.",
      "Take wudu or sit down if you are standing.",
      "Say one calm sentence only after your breathing settles.",
    ],
    challengeTitle: "Silent Reset",
    challengePrompt: "Catch one angry moment today and delay your response by 90 seconds.",
  },
  patience: {
    id: "patience",
    label: "Patience",
    tagline: "Steady hearts move with prayer, not panic.",
    accentClass: "from-emerald-500 to-teal-600",
    surfaceClass: "bg-emerald-50",
    borderClass: "border-emerald-200",
    icon: "Hourglass",
    keywords: ["wait", "waiting", "patient", "patience", "sabr", "delay", "hard", "tired", "stress", "frustrated"],
    ayah: {
      reference: "2:153",
      source: "Al Quran Cloud fallback cache",
      arabic: "اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
      english: "Seek help through patience and prayer. Surely Allah is with the patient.",
      urdu: "صبر اور نماز سے مدد لو، بے شک اللہ صبر کرنے والوں کے ساتھ ہے۔",
    },
    explanation:
      "Patience in the Quran is active, not passive. It means holding yourself steady while turning to Allah with discipline.",
    actionSteps: [
      "Name the test instead of calling everything a disaster.",
      "Pray two focused rak'ahs or make a short dua right now.",
      "Do the next right step, not the whole week at once.",
    ],
    challengeTitle: "Small Sabr",
    challengePrompt: "When delayed today, replace one complaint with one dua.",
  },
  jealousy: {
    id: "jealousy",
    label: "Jealousy",
    tagline: "Their gift is not proof that yours is missing.",
    accentClass: "from-fuchsia-500 to-purple-600",
    surfaceClass: "bg-fuchsia-50",
    borderClass: "border-fuchsia-200",
    icon: "Sparkles",
    keywords: ["jealous", "jealousy", "envy", "compare", "comparison", "why them", "resent", "insecure", "left behind"],
    ayah: {
      reference: "4:32",
      source: "Al Quran Cloud fallback cache",
      arabic: "وَلَا تَتَمَنَّوْا مَا فَضَّلَ اللَّهُ بِهِ بَعْضَكُمْ عَلَىٰ بَعْضٍ",
      english: "Do not crave what Allah has given some of you over others.",
      urdu: "اور اس چیز کی تمنا نہ کرو جس میں اللہ نے تم میں سے بعض کو بعض پر فضیلت دی ہے۔",
    },
    explanation:
      "Comparison drains gratitude fast. The ayah redirects your eyes from someone else's lane back to your own responsibility and provision.",
    actionSteps: [
      "Mute one comparison trigger for the next 24 hours.",
      "Write one blessing Allah already gave you.",
      "Make a sincere dua for the person you envied.",
    ],
    challengeTitle: "No Compare Hour",
    challengePrompt: "Avoid one comparison spiral and replace it with gratitude.",
  },
  honesty: {
    id: "honesty",
    label: "Honesty",
    tagline: "Truth cleans what excuses keep dirty.",
    accentClass: "from-sky-500 to-cyan-600",
    surfaceClass: "bg-sky-50",
    borderClass: "border-sky-200",
    icon: "Shield",
    keywords: ["lied", "lie", "truth", "honest", "honesty", "fake", "pretend", "deceive", "cover up", "hid"],
    ayah: {
      reference: "9:119",
      source: "Al Quran Cloud fallback cache",
      arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ وَكُونُوا مَعَ الصَّادِقِينَ",
      english: "O believers, be mindful of Allah and be with the truthful.",
      urdu: "اے ایمان والو! اللہ سے ڈرو اور سچوں کے ساتھ ہو جاؤ۔",
    },
    explanation:
      "Truthfulness is not only about facts. It is about being aligned inside and outside, even when honesty costs comfort.",
    actionSteps: [
      "Fix one dishonest detail before the day ends.",
      "Choose a direct sentence instead of a polished excuse.",
      "Ask yourself what truth would look like if Allah alone heard it.",
    ],
    challengeTitle: "Truth Check",
    challengePrompt: "Correct one small lie, exaggeration, or hidden detail today.",
  },
  sadness: {
    id: "sadness",
    label: "Sadness",
    tagline: "Heavy hearts still have a place to rest.",
    accentClass: "from-indigo-500 to-blue-600",
    surfaceClass: "bg-indigo-50",
    borderClass: "border-indigo-200",
    icon: "Moon",
    keywords: ["sad", "down", "lonely", "empty", "hurt", "broken", "cry", "crying", "lost", "depressed"],
    ayah: {
      reference: "13:28",
      source: "Al Quran Cloud fallback cache",
      arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
      english: "Surely in the remembrance of Allah do hearts find rest.",
      urdu: "خبردار! اللہ کے ذکر سے دلوں کو اطمینان ملتا ہے۔",
    },
    explanation:
      "The Quran does not deny pain. It gives the heart a stabilizer: remembrance that slowly returns inner calm.",
    actionSteps: [
      "Whisper one dhikr for a full minute without multitasking.",
      "Step outside or change rooms before the sadness deepens.",
      "Reach out to one safe person instead of isolating silently.",
    ],
    challengeTitle: "One Minute Dhikr",
    challengePrompt: "Pause the scroll and spend one minute in focused dhikr.",
  },
  gratitude: {
    id: "gratitude",
    label: "Gratitude",
    tagline: "Notice more, and your heart stops starving.",
    accentClass: "from-amber-500 to-yellow-500",
    surfaceClass: "bg-amber-50",
    borderClass: "border-amber-200",
    icon: "Sun",
    keywords: ["grateful", "gratitude", "thankful", "blessed", "alhamdulillah", "good day", "happy", "content"],
    ayah: {
      reference: "14:7",
      source: "Al Quran Cloud fallback cache",
      arabic: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
      english: "If you are grateful, I will surely increase you.",
      urdu: "اگر تم شکر کرو گے تو میں تمہیں اور زیادہ دوں گا۔",
    },
    explanation:
      "Gratitude in the Quran is a growth habit. When you name blessings clearly, your relationship with them changes.",
    actionSteps: [
      "Write one blessing you usually overlook.",
      "Thank Allah out loud for something small but real.",
      "Share one good thing without showing off.",
    ],
    challengeTitle: "Three Blessings",
    challengePrompt: "List three blessings before sleeping tonight.",
  },
  trust: {
    id: "trust",
    label: "Trust",
    tagline: "When you cannot control the outcome, anchor the heart.",
    accentClass: "from-teal-500 to-cyan-500",
    surfaceClass: "bg-teal-50",
    borderClass: "border-teal-200",
    icon: "Anchor",
    keywords: ["anxious", "anxiety", "worried", "worry", "fear", "afraid", "future", "uncertain", "panic", "overthinking"],
    ayah: {
      reference: "65:3",
      source: "Al Quran Cloud fallback cache",
      arabic: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ",
      english: "Whoever puts trust in Allah, then He is enough for them.",
      urdu: "اور جو اللہ پر بھروسا کرے تو وہ اس کے لیے کافی ہے۔",
    },
    explanation:
      "Trust in Allah is not giving up effort. It means doing your part without letting fear become your lord.",
    actionSteps: [
      "Separate what you can do today from what you cannot control.",
      "Turn one worry into one written dua.",
      "Close the loop on one small task that keeps feeding anxiety.",
    ],
    challengeTitle: "Worry to Dua",
    challengePrompt: "Convert one repeated worry into one specific dua today.",
  },
};

export const THEME_ORDER: ThemeId[] = [
  "anger",
  "patience",
  "jealousy",
  "honesty",
  "sadness",
  "gratitude",
  "trust",
];

export const EXAMPLE_INPUTS = [
  "I got angry at my brother.",
  "I feel jealous of my friend's success.",
  "I lied to avoid getting blamed.",
  "I feel anxious about the future.",
  "I am tired of waiting for things to improve.",
];
